### ISSUE TITLE
Masse dritt kode

### ISSUE THREAD

**Issue by eskoa001** [einaraarnaes/IT2#2]
Hei, gikk gjennom koden her og la merke til t mye av det var veldig dritt. Tror vi trenger noen som kan fikse det, litt ASAP pls.

**Comment by einaraarnaes** [comment]
Fukc of you piece of shit.

**Comment by eskoa001** [comment]
@einaraarnaes kan dessverre ikke gjøre noe med din mangel av ferdigheter

**Comment by eskoa001** [comment]
@einaraarnaes   ikke test meg

**Comment by ShaileshS1702** [comment]
Koden printer hei 20 ganger, men jeg vil gjøre 25 ganger, kan du fikse dette?
